name: aplimedia grid
favicon: null
layout_spectrum: 0.8209343960043043
typography_spectrum: 0.7601370555348694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.11792708281427622
  lightness: 0.9626879789866507
  saturation: 0.029730617767199874
  rhythmicContrast: 0.4172904775477946
purpose: []
